## 解线性方程组

just use numpy.linalg.solve

here there is an equation like the following :

$4x_1+4x_2=5$

$2x_1-4x_2=1$

In [27]:
import numpy as np

A = np.array([[4,4],[2,-4]])
b = np.array([5,1])

X=np.linalg.solve(A,b)

In [28]:
X

array([ 1.  ,  0.25])

In [3]:
print(np.dot(A,X))

[ 5.  1.]


Identity matrix just use numpy.identity

indentity , two parameters, one is the dimenstion, the other is the data type. default dtype is float.

note identity matrix is square

In [4]:
I = np.identity(5, dtype=int)
print(I)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [5]:
I = np.identity(5)
print(I)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [6]:
I = np.identity(5,dtype=float)
print(I)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


**for non-square matrix, use np.ones**

In [2]:
help(np.eye)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    --------
    identity : (almost) equivalent function
    diag : diagonal 2-D array from a 1-D array specified by the user.
    
    Examples
    --------
    >>> np.eye(2, dtype=int)
    arra

In [7]:
I = np.eye(2,4)
print(I)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


In [8]:
I = np.eye(4,k=1)
print(I)

[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [9]:
I = np.eye(4,k=-1)
print(I)

[[ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


## Inverse 

solve A's inverse 

AI -> IA^{-1}   

np.linalg.inv

In [12]:
print(A)
invA =  np.linalg.inv(A)
print(invA)

[[ 4 -2]
 [ 2 -4]]
[[ 0.33333333 -0.16666667]
 [ 0.16666667 -0.33333333]]


In [15]:
b = np.array([[2,3,4],[5,6,7]])
b.shape

(2, 3)

In [16]:
c = np.linalg.inv(b) # this will not work, because inverse can only be applied on square matrix

LinAlgError: Last 2 dimensions of the array must be square

## transpose 


np.transpose, or ndarray.T

In [18]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #(4,3)
transA = A.transpose((1,0))
print("A=\n",A, "\ntranspose is \n ", transA)

A=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
transpose is 
  [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [21]:
A = np.array([
              [[1,11],[2,22],[3,33]],
              [[4,44],[5,55],[6,66]],
              [[7,77],[8,88],[9,99]],
              [[10,1010],[11,1111],[12,1212]]
               ]) #(4,3,2)
A.shape
transA = A.transpose((1,0,2)) # 
print("A=\n",A, "\ntranspose is \n ", transA) 

A=
 [[[   1   11]
  [   2   22]
  [   3   33]]

 [[   4   44]
  [   5   55]
  [   6   66]]

 [[   7   77]
  [   8   88]
  [   9   99]]

 [[  10 1010]
  [  11 1111]
  [  12 1212]]] 
transpose is 
  [[[   1   11]
  [   4   44]
  [   7   77]
  [  10 1010]]

 [[   2   22]
  [   5   55]
  [   8   88]
  [  11 1111]]

 [[   3   33]
  [   6   66]
  [   9   99]
  [  12 1212]]]


In [23]:
A = np.array([1,2,3])
B = np.atleast_2d(A)
print(B)

[[1 2 3]]


In [7]:
x = np.array([1.,2.,3.,4.])
y=x[:,np.newaxis]
print(y)
z= y.transpose()
print("\n",z)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]]

 [[ 1.  2.  3.  4.]]


In [12]:
x.shape

(4,)

In [11]:
print(x)

[ 1.  2.  3.  4.]


In [9]:
print(x.transpose())

[ 1.  2.  3.  4.]


In [10]:
print(x.T)

[ 1.  2.  3.  4.]


In [14]:
y = x.reshape(x.shape[0],1)
print(y)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]]


## multiply 

by a scala

In [35]:
xby5 = np.multiply(5,y)
print(xby5)

[[  5.]
 [ 10.]
 [ 15.]
 [ 20.]]


In [45]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print("x1=\n", x1,"\nx2=\n",x2,"\nx1 multiply x2=\n", np.multiply(x1, x2))
print("x1=\n", x1,"\nx2=\n",x2,"\nx1 * x2=\n", x1*x2)
print("x1=\n", x1,"\nx2=\n",x2,"\nx2 arraydot** x1=\n", np.dot(x2,x1))
# ndarray multiply 和 * 一样，都指相应元素相乘，又叫数量积、点乘
#  * 和ltiply一样，都指相应元素相乘，又叫数量积、点乘
# dot为矢量积、叉乘

x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x1 multiply x2=
 [[  0.   1.   4.]
 [  0.   4.  10.]
 [  0.   7.  16.]]
x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x1 * x2=
 [[  0.   1.   4.]
 [  0.   4.  10.]
 [  0.   7.  16.]]
x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x2 ** x1=
 [ 15.  18.  21.]


In [47]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print("x1=\n", x1,"\nx2=\n",x2,"\nx1 multiply x2=\n", np.multiply(np.matrix(x1), np.matrix(x2)))
print("x1=\n", x1,"\nx2=\n",x2,"\nx2 * x1=\n", np.matrix(x2)*np.matrix(x1))
print("x1=\n", x1,"\nx2=\n",x2,"\nx2 matrixdot x1=\n", np.dot(np.matrix(x2),np.matrix(x1)))
# matrix 而言，np.multiply 为数量积、点乘
# 而* 为叉乘、矢量积；.dot为矢量积、叉乘。

x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x1 multiply x2=
 [[  0.   1.   4.]
 [  0.   4.  10.]
 [  0.   7.  16.]]
x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x2 * x1=
 [[ 15.  18.  21.]]
x1=
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] 
x2=
 [ 0.  1.  2.] 
x2 matrixdot x1=
 [[ 15.  18.  21.]]


总结一下，**np.multiply对matrix and array , 都是数量积、点乘**

**符号* 对二者意义不同**

**dot则对二者意义相同，都是矢量积、叉乘**

## 手工解线性方程组的方法

step1. find the special solution for$Ax = b $

step2. find all solutions for $Ax=0$

step3. combine solutions from 1 and 2 to the general solution

### how to find the special solution for $Ax=b$

#### step1 

write the equation into augmented matrix

[A|b]

Gaussian elimination use elementary transformation to bring an equation into reduced row echelon form 

* row echelon form 

* every pivot is 1

* the pivot is the only non-zero entry in its column

transform [A|b]   into the form of **row-echelon form阶梯形**


pivot  **一行中开头的系数** ，for reduce echelon form , 需要pivot 变换为1

pivot对应的变量为basic variables, others are called free variables.

using pivot columns to get the particular solutions


#### step2

express the non-pivot columns in terms of sums and multiples of the pivot columns that are on their left

the simplest way to solve $Ax=0$ is **minus-one trick**

add the rows with the pivot = -1 and other elements as 0 , so that it is a diagonal matrix 

###  伪逆Moore-Penrose pseudo-inverse, np.linalg.pinv(a)

$Ax=b$

$A^TAx=A^Tb$

$x=(AA^T)^{-1}A^Tb$

In [26]:
A = np.array([[4,-2],[2,-4]])
b = np.array([5,1])

X=np.linalg.solve(A,b)
pinvA = np.linalg.pinv(A)
Y=np.dot(pinvA,b)

print((Y==X).all())  #this result is weird

print(X.shape, Y.shape)

print("X=\n",X,"\n")
print("Y=\n",Y)



False
(2,) (2,)
X=
 [ 1.5  0.5] 

Y=
 [ 1.5  0.5]


In [27]:
np.linalg.matrix_rank(A)

2

### Vector Spaces

linear independent

linear dependent 

Basis:

intuitive explanation

It is possible to find a set of vectors with which we can represent every vector in the vector space by adding them together and scaling them. This set of vectors is a *basis*


Generating set

generating span

a basis is a minimal generating set and a maximal linearly independent set of vectors 

**rank**

the number of linearly independent columns of a matrix $A \in R^{m \times n}$ equals the number of linearly independent rows and is called the *rank* of $A$ and is denoted as $rk(A)$

for $A \in R^{m \times n}$, the subspace of solutions for $Ax=0$ is called $kernal$ or $null space$, dimension is $n-rk(A)$

**full rank **

**rank deficient** if a matrix has no full rank, it is called to be rank deficient 

### Linear Mapping

vectors are objects that can be added together and multiplied by a scalar. and the result object is also a vector.

we wish to preserve this property when applying the mapping.

a mapping $\phi : V \rightarrow W$ preserves this structure of the vector space if : 

$$\phi(x+y)=\phi(x) + \phi(y) $$
$$\phi(\lambda x)=\lambda\phi(x)$$

Definitions of linear mapping

we represent linear mapping as matrix , we keep in mind what a matrix represent : a linear mapping or a collection of vectors.




### matrix rank

In [20]:
from numpy.linalg import matrix_rank
A = np.array([[4,-2],[2,-4]])

matrix_rank(A)

2

In [21]:
A = np.array([[1,4,-2],[2,2,-4]])
matrix_rank(A)

2

In [60]:
A = np.array([[1,2,-1,0],[1,0,0,1]])
A.shape

matrix_rank(A)

2

In [61]:
b=np.array([[0],[0]])
b.shape
print(b)

[[0]
 [0]]


In [62]:
x = np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

In [63]:
x = np.linalg.lstsq(A,b)

In [64]:
print(x)

(array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.]]), array([], dtype=float64), 2, array([ 2.49721204,  1.32813103]))


In [42]:
import scipy as scipy


ns = scipy.linalg.null_space(A)

AttributeError: module 'scipy.linalg' has no attribute 'null_space'

In [44]:
help(scipy.linalg.orth)

Help on function orth in module scipy.linalg.decomp_svd:

orth(A)
    Construct an orthonormal basis for the range of A using SVD
    
    Parameters
    ----------
    A : (M, N) array_like
        Input array
    
    Returns
    -------
    Q : (M, K) ndarray
        Orthonormal basis for the range of A.
        K = effective rank of A, as determined by automatic cutoff
    
    See also
    --------
    svd : Singular value decomposition of a matrix



In [49]:
print(scipy.version.version)

0.19.1


### 遗留问题

求解零空间的python方法。

可以用高斯消减+minus-1手工方法

用python  np.linalg.solve不行

使用np.linalg.lstsq 得出的结果也无法验证。